import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Amazon Seller Central Replica',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>

                <header>
                    <h1>Amazon Seller Central Replica</h1>
                </header>

                <nav>
                    <a href="#">Home</a>
                    <a href="#">Orders</a>
                    <a href="#">Inventory</a>
                    <a href="#">Reports</a>
                    <a href="#">Settings</a>
                </nav>
                <section>
                    <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%" className="p-4 m-4">
                        {children}
                    </Theme>
                </section>
                <footer>
                    <p>&copy; 2023 Amazon Seller Central Replica. All rights reserved.</p>
                </footer>
            </body>
        </html >
    )
}
